sudo: false

language: node_js
node_js:
  - "10"

  env:
  - JWT_SECRET=supersecret SENTRY_DNS=supersecret

services: mongodb

cache:
  directories:
    - "node_modules"

before_install:
  - cd ./server

install:
  - npm install

script:
  - npm test
