sudo: false

language: node_js
node_js:
  - "10"

services: mongodb

cache:
  directories:
    - "node_modules"

before_install:
  - cd ./server

install:
  - npm install

before_script:
  - cp .env.example .env

script:
  - npm test
