language: node_js
node_js:
  - "10"
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
env:
  - JWT_SECRET=supersecret SENTRY_DNS=supersecret
install:
  - npm install
script:
  - npm test