version: '3'
services:
  #######################
  # MongoDB
  #######################
  mongo:
    image: mongo:4.0
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
  #######################
  # Server
  #######################
  server:
    build: ./server
    expose:
     - ${APP_SERVER_PORT}
    ports:
     - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
     - ./server:/usr/src/app/server
     - /usr/src/app/server/node_modules
    env_file: .env
    links:
     - mongo
    depends_on:
     - mongo
  #######################
  # Client
  #######################
  client:
    build: ./client
    expose:
      - ${REACT_APP_PORT}
    ports:
     - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
     - ./client:/usr/src/app/client
     - /usr/src/app/client/node_modules
    env_file: .env
    links:
     - server

