version: '3'
services:
  api:
    build: .
    ports:
     - "8080:8080"
    env_file: .env
    links:
     - db 
    depends_on: 
     - db 
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
  db:
    image: mongo:4.0
    ports: 
      - "27017:27017"
